import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  LayoutDashboard, 
  ShieldAlert, 
  Bell, 
  Settings, 
  LogOut, 
  User,
  Banknote,
  Award,
  TrendingUp,
  Download,
  Share2,
  CheckCircle2,
  Mail,
  ArrowRight,
  ShieldCheck,
  Landmark,
  Info,
  Loader2
} from 'lucide-react';
import { getTrustScore, getToken } from '../services/api';

function TrustScore() {
  const navigate = useNavigate();
  const [trustData, setTrustData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  const onLogout = () => {
    localStorage.removeItem('token');
    navigate('/login');
  };
  const onNavigate = (path) => navigate(`/${path}`);

  useEffect(() => {
    const token = getToken();
    if (!token) {
      navigate('/login');
      return;
    }
    fetchTrustScore();
  }, []);

  const fetchTrustScore = async () => {
    try {
      setLoading(true);
      const response = await getTrustScore();
      const data = response?.data || response;
      setTrustData(data && typeof data === 'object' ? data : {});
    } catch (err) {
      setError('Using demo TrustScore data');
      setTrustData({});
    } finally {
      setLoading(false);
    }
  };

  const safeNumber = (val, fallback) => {
    const n = Number(val);
    return isNaN(n) ? fallback : n;
  };

  const safeString = (val, fallback) => {
    if (!val) return fallback;
    if (typeof val === 'string') return val;
    if (typeof val === 'number') return String(val);
    return fallback;
  };

  const score = safeNumber(trustData?.score || trustData?.trust_score, 74);
  const scoreLabel = safeString(trustData?.score_label || trustData?.rating, 'Good Standing');
  const explanation = safeString(trustData?.explanation || trustData?.narrative, 'Your TrustScore of 74 indicates a high level of operational reliability. This score is generated by analyzing transaction patterns, liquidity ratios, and fraud prevention success over the past 90 days within the SquadMind ecosystem.');
  const revenueChange = safeNumber(trustData?.revenue_change, 12);
  const fraudAlerts = safeNumber(trustData?.fraud_alerts_count, 2);

  const scoreComponents = Array.isArray(trustData?.components || trustData?.breakdown) 
    ? (trustData?.components || trustData?.breakdown)
    : [
        { label: 'REVENUE CONSISTENCY', score: 22, max: 25, sub: '+2.4%', color: 'cyan' },
        { label: 'REPEAT CUSTOMERS', score: 18, max: 20, sub: 'STABLE', color: 'cyan' },
        { label: 'LOW FRAUD RATE', score: 18, max: 20, sub: 'EXCELLENT', color: 'emerald' },
        { label: 'CASHFLOW STABILITY', score: 16, max: 20, sub: 'STABLE', color: 'cyan' },
        { label: 'GROWTH TREND', score: 0, max: 15, sub: 'NEEDS IMPROVEMENT', color: 'red' },
      ];

  const getComponentColor = (comp) => {
    const sub = (comp.sub || comp.status || '').toLowerCase();
    if (sub.includes('needs') || comp.score === 0) return 'red';
    if (sub.includes('excellent')) return 'emerald';
    return 'cyan';
  };

  const getProgress = (comp) => {
    const s = comp.score ?? comp.value ?? 0;
    const m = comp.max ?? comp.max_score ?? 25;
    return `${Math.round((s / m) * 100)}%`;
  };

  // Gauge arc calculation
  const gaugePercent = score / 100;
  const gaugeAngle = gaugePercent * 180;
  const endX = 50 + 45 * Math.cos(Math.PI - (gaugeAngle * Math.PI / 180));
  const endY = 50 - 45 * Math.sin(gaugeAngle * Math.PI / 180);

  if (loading) {
    return (
      <div className="flex h-screen w-full items-center justify-center bg-[#f8fafc]">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-12 h-12 text-[#00d2ff] animate-spin" />
          <p className="text-slate-500 font-medium">Loading your TrustScore...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-screen w-full bg-[#f8fafc] font-outfit text-slate-900 overflow-hidden relative">
      
      <aside className="w-[260px] bg-[#001f3f] flex flex-col justify-between shrink-0 h-full overflow-y-auto hidden md:flex">
        <div>
          <div className="p-8 pb-10">
            <h1 className="text-2xl font-bold tracking-tight text-white mb-0">SquadMind AI</h1>
            <p className="text-[10px] text-slate-400 mt-1 uppercase tracking-widest font-medium">POWERED BY SQUAD</p>
          </div>
          <nav className="px-4 space-y-1">
            <button onClick={() => onNavigate('dashboard')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-400 hover:text-white hover:bg-[#112f4d]/50 rounded-lg transition-colors cursor-pointer">
              <LayoutDashboard className="w-5 h-5" />
              <span className="font-medium text-[15px]">Dashboard</span>
            </button>
            <button onClick={() => onNavigate('cashflow')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-400 hover:text-white hover:bg-[#112f4d]/50 rounded-lg transition-colors cursor-pointer">
              <Banknote className="w-5 h-5" />
              <span className="font-medium text-[15px]">Cash Flow</span>
            </button>
            <button onClick={() => onNavigate('frauddetection')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-400 hover:text-white hover:bg-[#112f4d]/50 rounded-lg transition-colors cursor-pointer">
              <ShieldAlert className="w-5 h-5" />
              <span className="font-medium text-[15px]">Fraud Detection</span>
            </button>
            <button onClick={() => onNavigate('alerts')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-400 hover:text-white hover:bg-[#112f4d]/50 rounded-lg transition-colors cursor-pointer">
              <Bell className="w-5 h-5" />
              <span className="font-medium text-[15px]">Alerts</span>
            </button>
            <button onClick={() => onNavigate('trustscore')} className="w-full flex items-center gap-3 px-4 py-3 bg-[#112f4d] text-white rounded-lg transition-colors cursor-pointer">
              <Award className="w-5 h-5 text-white" />
              <span className="font-medium text-[15px]">TrustScore</span>
            </button>
            <button onClick={() => onNavigate('settings')} className="w-full flex items-center gap-3 px-4 py-3 text-slate-400 hover:text-white hover:bg-[#112f4d]/50 rounded-lg transition-colors cursor-pointer">
              <Settings className="w-5 h-5" />
              <span className="font-medium text-[15px]">Settings</span>
            </button>
          </nav>
        </div>
        <div className="p-6 space-y-6">
          <div className="space-y-1">
            <button onClick={onLogout} className="w-full flex items-center gap-3 px-4 py-2 text-slate-400 hover:text-white transition-colors cursor-pointer">
              <LogOut className="w-4 h-4" />
              <span className="text-sm font-medium">Logout</span>
            </button>
          </div>
          <div className="pt-6 border-t border-white/5 flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-[#00d2ff] flex items-center justify-center text-[#001f3f] font-bold">
              <User className="w-5 h-5" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold text-white truncate">Lekan Adeyemi</p>
              <p className="text-[10px] text-slate-400 font-medium truncate">Merchant Admin</p>
            </div>
          </div>
        </div>
      </aside>

      <main className="flex-1 flex flex-col h-full overflow-y-auto pb-20 md:pb-0">
        <header className="h-16 md:h-20 bg-white border-b border-slate-100 flex items-center justify-between px-4 md:px-8 shrink-0">
          <h2 className="text-xl md:text-2xl font-bold text-slate-900 leading-tight">TrustScore™</h2>
          <div className="flex items-center gap-2 md:gap-4">
            <button className="p-2 text-slate-400 hover:text-slate-600 transition-colors">
              <Mail className="w-5 h-5" />
            </button>
            <button className="p-2 text-slate-400 hover:text-slate-600 transition-colors relative">
              <Bell className="w-5 h-5" />
              <div className="absolute top-2 right-2 w-2 h-2 bg-red-500 rounded-full border-2 border-white"></div>
            </button>
            <div className="w-9 h-9 md:w-10 md:h-10 rounded-full bg-slate-100 flex items-center justify-center border border-slate-200">
              <User className="w-4 h-4 md:w-5 md:h-5 text-slate-400" />
            </div>
          </div>
        </header>

        <div className="p-4 md:p-8 max-w-[1400px] w-full mx-auto">

          {error && (
            <div className="mb-6 p-4 bg-amber-50 rounded-2xl border border-amber-100 text-amber-600 text-sm font-medium">
              {error}
            </div>
          )}

          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 mb-10">
            
            <div className="lg:col-span-3 bg-white rounded-2xl md:rounded-[40px] p-8 md:p-12 shadow-sm border border-slate-100 flex flex-col items-center justify-center relative overflow-hidden">
              <div className="relative w-full max-w-[340px] aspect-[2/1] mb-8">
                <svg className="w-full h-full" viewBox="0 0 100 50">
                  <path d="M5,50 A45,45 0 0,1 95,50" fill="none" stroke="#f1f5f9" strokeWidth="10" strokeLinecap="round" />
                  <path 
                    d={`M5,50 A45,45 0 0,1 ${endX},${endY}`}
                    fill="none" stroke="#001f3f" strokeWidth="10" strokeLinecap="round" 
                  />
                </svg>
                <div className="absolute bottom-0 left-0 right-0 flex flex-col items-center">
                  <span className="text-4xl md:text-6xl font-bold text-slate-900">
                    {score}<span className="text-xl md:text-2xl text-slate-300">/100</span>
                  </span>
                </div>
              </div>

              <div className="inline-flex items-center gap-2 px-4 py-1 bg-emerald-50 text-emerald-600 rounded-full text-[10px] font-bold tracking-wider mb-6 border border-emerald-100 uppercase">
                <ShieldCheck className="w-3.5 h-3.5" />
                {scoreLabel}
              </div>

              <h3 className="text-xl md:text-2xl font-bold text-slate-900 mb-2 text-center">
                Score is {score >= 70 ? 'Healthy' : score >= 50 ? 'Moderate' : 'Needs Improvement'}
              </h3>
              <p className="text-slate-500 text-sm font-medium mb-10 text-center">Based on last 90 days of Squad transactions</p>

              <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
                <button
                  onClick={() => alert('Generating your lender-ready report...\n\nYour TrustScore report has been prepared. In production, this downloads a PDF you can share with any lender or bank.')}
                  className="flex items-center justify-center gap-2 bg-[#001f3f] text-white font-bold py-3.5 px-8 rounded-xl text-xs transition-all shadow-lg cursor-pointer hover:bg-[#002b55]"
                >
                  <Download className="w-4 h-4" />
                  Download Report
                </button>
                <button
                  onClick={() => alert('Share link copied!\n\nYour TrustScore report link is ready to share with lenders.')}
                  className="flex items-center justify-center gap-2 bg-white border border-slate-200 text-slate-600 font-bold py-3.5 px-8 rounded-xl text-xs transition-all cursor-pointer hover:bg-slate-50"
                >
                  <Share2 className="w-4 h-4" />
                  Share with Lender
                </button>
              </div>
            </div>

            <div className="bg-[#001f3f] rounded-2xl md:rounded-[40px] p-8 text-white relative overflow-hidden flex flex-col">
              <h4 className="text-lg font-bold mb-6">Instant Insights</h4>
              <div className="space-y-6 flex-1">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center shrink-0">
                    <TrendingUp className="w-5 h-5 text-emerald-400" />
                  </div>
                  <div>
                    <p className="text-sm font-bold">Revenue Up {revenueChange}%</p>
                    <p className="text-[10px] text-slate-400">Month-over-month growth trend is positive.</p>
                  </div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center shrink-0">
                    <ShieldAlert className="w-5 h-5 text-red-400" />
                  </div>
                  <div>
                    <p className="text-sm font-bold">Fraud Alerts</p>
                    <p className="text-[10px] text-slate-400">{fraudAlerts} flagged transactions requiring review.</p>
                  </div>
                </div>
              </div>
              <div className="mt-8 pt-6 border-t border-white/5">
                <div className="h-12 flex items-end gap-1">
                  {[30, 45, 35, 55, 40, 65, 50, 75, 60, 85].map((h, i) => (
                    <div key={i} className="flex-1 bg-[#00d2ff]/40 rounded-t-sm" style={{ height: `${h}%` }}></div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          <div className="mb-12">
            <div className="flex justify-between items-end mb-6">
              <div>
                <h3 className="text-xl font-bold text-slate-900 mb-1">Score Breakdown</h3>
                <p className="text-sm text-slate-400 font-medium">Individual metrics contributing to your overall score</p>
              </div>
              <button className="text-xs font-bold text-[#001f3f] hover:underline transition-all">View Historical Data</button>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
              {scoreComponents.map((metric, i) => {
                const color = metric.color || getComponentColor(metric);
                const progress = metric.progress || getProgress(metric);
                const scoreVal = metric.score ?? metric.value ?? 0;
                const maxVal = metric.max ?? metric.max_score ?? 25;
                const subLabel = metric.sub || metric.status || '';
                return (
                  <div key={i} className={`bg-white rounded-2xl p-6 shadow-sm border border-slate-100 flex flex-col ${color === 'red' ? 'border-l-4 border-l-red-500' : ''}`}>
                    <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-4 leading-tight">{metric.label || metric.name}</p>
                    <div className="flex items-baseline justify-between mb-4">
                      <span className="text-2xl font-bold text-slate-900">
                        {scoreVal}<span className="text-sm text-slate-300">/{maxVal}</span>
                      </span>
                      <span className={`text-[9px] font-black tracking-tighter ${color === 'red' ? 'text-red-500' : color === 'emerald' ? 'text-emerald-500' : 'text-[#00d2ff]'}`}>
                        {subLabel}
                      </span>
                    </div>
                    <div className="mt-auto h-1.5 bg-slate-50 rounded-full overflow-hidden">
                      <div className={`h-full ${color === 'red' ? 'bg-red-500' : color === 'emerald' ? 'bg-emerald-500' : 'bg-cyan-400'}`} style={{ width: progress }}></div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
            <div className="bg-white rounded-[32px] p-8 md:p-10 shadow-sm border border-slate-100">
              <div className="flex items-center gap-3 mb-8">
                <div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center">
                  <Info className="w-5 h-5 text-[#00d2ff]" />
                </div>
                <h4 className="text-lg font-bold text-slate-900">What This Means</h4>
              </div>
              <p className="text-slate-500 text-sm md:text-base leading-relaxed mb-10 font-medium opacity-90">
                {explanation}
              </p>
              <div className="p-6 bg-[#f8fafc] rounded-2xl border-l-4 border-slate-900">
                <h5 className="text-sm font-bold text-slate-900 mb-2">Growth Opportunity</h5>
                <p className="text-xs text-slate-500 leading-relaxed font-medium">
                  Your Growth Trend metric is currently low because of seasonal adjustments. Reaching a score of 80+ could unlock lower interest rates from our lending partners.
                </p>
              </div>
            </div>

            <div className="bg-white rounded-[32px] p-8 md:p-10 shadow-sm border border-slate-100 flex flex-col">
              <div className="flex items-center gap-3 mb-8">
                <div className="w-10 h-10 rounded-xl bg-cyan-50 flex items-center justify-center">
                  <Landmark className="w-5 h-5 text-[#00d2ff]" />
                </div>
                <h4 className="text-lg font-bold text-slate-900">Lender Ready</h4>
              </div>
              <div className="space-y-5 mb-10 flex-1">
                {[
                  "Identity Verified",
                  "Squad Account Active (> 1yr)",
                  "Transaction History Audited",
                  "TrustScore Meeting Minimum Threshold"
                ].map((step, i) => (
                  <div key={i} className="flex items-center gap-4">
                    <CheckCircle2 className="w-5 h-5 text-emerald-500" />
                    <span className="text-sm font-bold text-slate-700">{step}</span>
                  </div>
                ))}
              </div>
              <div className="p-8 bg-cyan-50/30 rounded-3xl border border-cyan-100/50">
                <p className="text-xs font-bold text-slate-500 mb-6 text-center">You are ready to apply for business credit</p>
                <button
                  onClick={() => alert('Connecting you to our lending partners...\n\nFeature launching Q3 2026. Your TrustScore of ' + score + '/100 qualifies you for loans from our partner institutions.')}
                  className="w-full bg-[#00d2ff] hover:bg-[#00d2ff]/90 text-white font-black py-4 rounded-xl flex items-center justify-center gap-3 transition-all shadow-lg shadow-[#00d2ff]/20 cursor-pointer"
                >
                  Find Lenders
                  <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>

          <footer className="py-12 border-t border-slate-100 mt-12 text-center md:text-left flex flex-col md:flex-row justify-between items-center gap-6">
            <div className="flex items-center gap-8 text-[10px] font-bold text-slate-300 uppercase tracking-widest">
              <span className="text-slate-400">POWERED BY SQUAD</span>
              <a href="#" className="hover:text-slate-500 transition-colors">Privacy Policy</a>
              <a href="#" className="hover:text-slate-500 transition-colors">Terms of Service</a>
            </div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-widest">© 2026 SQUADMIND v2.4.1</p>
          </footer>
        </div>
      </main>

      <nav className="fixed bottom-0 left-0 w-full bg-white border-t border-slate-100 flex items-center justify-around py-3 md:hidden z-50">
        <button onClick={() => onNavigate('dashboard')} className="flex flex-col items-center gap-1 text-slate-400">
          <LayoutDashboard className="w-5 h-5" />
          <span className="text-[10px] font-bold">Home</span>
        </button>
        <button onClick={() => onNavigate('cashflow')} className="flex flex-col items-center gap-1 text-slate-400">
          <Banknote className="w-5 h-5" />
          <span className="text-[10px] font-bold">Cash</span>
        </button>
        <button onClick={() => onNavigate('frauddetection')} className="flex flex-col items-center gap-1 text-slate-400">
          <ShieldAlert className="w-5 h-5" />
          <span className="text-[10px] font-bold">Fraud</span>
        </button>
        <button onClick={() => onNavigate('trustscore')} className="flex flex-col items-center gap-1 text-[#001f3f]">
          <Award className="w-5 h-5" />
          <span className="text-[10px] font-bold">Score</span>
        </button>
        <button onClick={() => onNavigate('settings')} className="flex flex-col items-center gap-1 text-slate-400">
          <Settings className="w-5 h-5" />
          <span className="text-[10px] font-bold">More</span>
        </button>
      </nav>
    </div>
  );
}

export default TrustScore;
