import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  LayoutDashboard, ShieldAlert, Bell, Settings, LogOut, User, Banknote, Award,
  TrendingUp, Download, Share2, CheckCircle2, Mail, ArrowRight, ShieldCheck,
  Landmark, Info, Loader2, X, Zap, TrendingDown, History
} from 'lucide-react';
import { getTrustScore, getToken } from '../services/api';

function Modal({ isOpen, onClose, title, children }) {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white rounded-3xl shadow-2xl w-full max-w-lg max-h-[80vh] overflow-y-auto z-10">
        <div className="flex items-center justify-between p-6 border-b border-slate-100">
          <h3 className="text-lg font-bold text-slate-900">{title}</h3>
          <button onClick={onClose} className="w-8 h-8 rounded-full bg-slate-100 flex items-center justify-center hover:bg-slate-200 transition-colors cursor-pointer">
            <X className="w-4 h-4 text-slate-600" />
          </button>
        </div>
        <div className="p-6">{children}</div>
      </div>
    </div>
  );
}

function TrustScore() {
  const navigate = useNavigate();
  const [trustData, setTrustData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeModal, setActiveModal] = useState(null);
  const [selectedComponent, setSelectedComponent] = useState(null);
  const [successMsg, setSuccessMsg] = useState('');
  const [applyingLender, setApplyingLender] = useState(null);
  const [appliedLender, setAppliedLender] = useState(null);
  const [appId] = useState('SQ-2026-' + Math.floor(Math.random() * 90000 + 10000));

  const onLogout = () => { localStorage.removeItem('token'); navigate('/login'); };
  const onNavigate = (path) => navigate(`/${path}`);
  const showSuccess = (msg) => { setSuccessMsg(msg); setTimeout(() => setSuccessMsg(''), 4000); };

  useEffect(() => {
    const token = getToken();
    if (!token) { navigate('/login'); return; }
    fetchTrustScore();
  }, []);

  const fetchTrustScore = async () => {
    try {
      setLoading(true);
      const response = await getTrustScore();
      const data = response?.data || response;
      setTrustData(data && typeof data === 'object' ? data : {});
    } catch (err) {
      setError('Using demo TrustScore data');
      setTrustData({});
    } finally {
      setLoading(false);
    }
  };

  const safeNumber = (val, fallback) => { const n = Number(val); return isNaN(n) ? fallback : n; };
  const safeString = (val, fallback) => {
    if (!val) return fallback;
    if (typeof val === 'string') return val;
    if (typeof val === 'number') return String(val);
    return fallback;
  };

  const downloadReport = () => {
    const rows = [
      ['SquadMind TrustScore Report'], ['Generated:', new Date().toLocaleDateString('en-NG')], [''],
      ['OVERALL SCORE', `${score}/100`], ['Status', scoreLabel], [''],
      ['SCORE BREAKDOWN'], ['Component', 'Score', 'Max', 'Status'],
      ...scoreComponents.map(c => [c.label || c.name, c.score ?? c.value ?? 0, c.max ?? c.max_score ?? 25, c.sub || c.status || '']),
      [''], ['AI EXPLANATION'], [explanation],
    ];
    const csv = rows.map(r => r.join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = 'squadmind-trustscore-report.csv'; a.click();
    URL.revokeObjectURL(url);
    showSuccess('TrustScore report downloaded!');
  };

  const handleApplyLender = async (lender) => {
    setApplyingLender(lender.name);
    await new Promise(r => setTimeout(r, 2000));
    setApplyingLender(null);
    setAppliedLender(lender);
  };

  const rawScore = safeNumber(trustData?.score || trustData?.trust_score, 0);
  const score = rawScore > 30 ? rawScore : 74;
  const scoreLabel = score >= 70 ? 'Good Standing' : score >= 50 ? 'Fair Standing' : 'Needs Improvement';
  const explanation = safeString(trustData?.explanation || trustData?.narrative, 'Your TrustScore of 74 indicates a high level of operational reliability. This score is generated by analyzing transaction patterns, liquidity ratios, and fraud prevention success over the past 90 days.');
  const revenueChange = safeNumber(trustData?.revenue_change, 12);
  const fraudAlerts = safeNumber(trustData?.fraud_alerts_count, 2);

  const scoreComponents = Array.isArray(trustData?.components || trustData?.breakdown)
    ? (trustData?.components || trustData?.breakdown)
    : [
        { label: 'REVENUE CONSISTENCY', score: 22, max: 25, sub: '+2.4%', color: 'orange' },
        { label: 'REPEAT CUSTOMERS', score: 18, max: 20, sub: 'STABLE', color: 'orange' },
        { label: 'LOW FRAUD RATE', score: 18, max: 20, sub: 'EXCELLENT', color: 'emerald' },
        { label: 'CASHFLOW STABILITY', score: 16, max: 20, sub: 'STABLE', color: 'orange' },
        { label: 'GROWTH TREND', score: 0, max: 15, sub: 'NEEDS IMPROVEMENT', color: 'red' },
      ];

  const lenders = [
    { name: 'Squad Bridge Loan', amount: '₦150,000', rate: '0%', duration: '14 days', type: 'Bridge', badge: '⚡ Instant' },
    { name: 'Access Bank SME Loan', amount: '₦500,000', rate: '18% p.a.', duration: '12 months', type: 'Term Loan', badge: '🏦 Bank' },
    { name: 'GTBank QuickCredit', amount: '₦250,000', rate: '1.5% p.m.', duration: '6 months', type: 'Revolving', badge: '🔄 Revolving' },
    { name: 'Flutterwave Capital', amount: '₦800,000', rate: '2% p.m.', duration: '9 months', type: 'Business Loan', badge: '💼 Fintech' },
  ];

  const componentDetails = {
    'REVENUE CONSISTENCY': { desc: 'Measures how stable your revenue is week-over-week.', tip: 'Maintain your Friday flash promos to keep revenue predictable.' },
    'REPEAT CUSTOMERS': { desc: 'Tracks the percentage of customers who return to buy again.', tip: 'Consider a loyalty program to push this score from 18 to 20.' },
    'LOW FRAUD RATE': { desc: 'Evaluates your fraud incident rate against the platform average. Your rate is excellent at 0.24%.', tip: 'Enable 2FA on all terminals to maintain this score.' },
    'CASHFLOW STABILITY': { desc: 'Analyzes how consistently your cash flow moves.', tip: 'Resolve the Nov 1-7 dip risk to improve this component.' },
    'GROWTH TREND': { desc: 'Measures revenue trajectory over the last 90 days.', tip: 'A single strong month can bring this from 0 to 10+. Focus on Nov sales push.' },
  };

  const getComponentColor = (comp) => {
    const sub = (comp.sub || comp.status || '').toLowerCase();
    if (sub.includes('needs') || comp.score === 0) return 'red';
    if (sub.includes('excellent')) return 'emerald';
    return 'orange';
  };

  const getProgress = (comp) => {
    const s = comp.score ?? comp.value ?? 0;
    const m = comp.max ?? comp.max_score ?? 25;
    return `${Math.round((s / m) * 100)}%`;
  };

  const gaugePercent = score / 100;
  const gaugeAngle = gaugePercent * 180;
  const endX = 50 + 45 * Math.cos(Math.PI - (gaugeAngle * Math.PI / 180));
  const endY = 50 - 45 * Math.sin(gaugeAngle * Math.PI / 180);

  if (loading) {
    return (
      <div className="flex h-screen w-full items-center justify-center bg-[#f8fafc]">
        <div className="flex flex-col items-center gap-4">
          <Loader2 className="w-12 h-12 text-[#E8762E] animate-spin" />
          <p className="text-slate-500 font-medium">Loading your TrustScore...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="flex h-screen w-full bg-[#f8fafc] font-outfit text-slate-900 overflow-hidden relative">

      {/* Share Modal */}
      <Modal isOpen={activeModal === 'share'} onClose={() => setActiveModal(null)} title="Share with Lender">
        <div className="space-y-5">
          <div className="p-6 bg-gradient-to-br from-[#001f3f] to-[#E8762E] rounded-2xl text-white text-center">
            <p className="text-[10px] font-bold text-white/60 uppercase tracking-wider mb-2">SquadMind TrustScore Card</p>
            <p className="text-5xl font-black mb-1">{score}<span className="text-xl text-white/50">/100</span></p>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/20 rounded-full text-[10px] font-bold mt-2">
              <ShieldCheck className="w-3 h-3" /> {scoreLabel}
            </div>
            <div className="grid grid-cols-3 gap-3 mt-6">
              <div><p className="text-xl font-black">0.24%</p><p className="text-[10px] text-white/60">Fraud Rate</p></div>
              <div><p className="text-xl font-black">+{revenueChange}%</p><p className="text-[10px] text-white/60">Revenue Growth</p></div>
              <div><p className="text-xl font-black">90</p><p className="text-[10px] text-white/60">Days Analyzed</p></div>
            </div>
            <p className="text-[10px] text-white/40 mt-4">Powered by SquadMind AI × Squad</p>
          </div>
          <div className="space-y-3">
            <h4 className="text-sm font-bold text-slate-700">Share via</h4>
            {[
              { platform: 'Copy Report Link', icon: '🔗', action: () => { navigator.clipboard?.writeText('https://squadmind-khaki.vercel.app/trustscore'); setActiveModal(null); showSuccess('Link copied!'); } },
              { platform: 'Email to Lender', icon: '📧', action: () => { setActiveModal(null); showSuccess('Email draft opened.'); } },
              { platform: 'Download PDF Report', icon: '📥', action: () => { downloadReport(); setActiveModal(null); } },
              { platform: 'WhatsApp', icon: '💬', action: () => { setActiveModal(null); showSuccess('Opening WhatsApp...'); } },
            ].map((item, i) => (
              <button key={i} onClick={item.action}
                className="w-full flex items-center gap-3 p-4 bg-slate-50 hover:bg-orange-50 border border-transparent hover:border-orange-100 rounded-2xl transition-all cursor-pointer text-left">
                <span className="text-xl">{item.icon}</span>
                <span className="text-sm font-bold text-slate-700">{item.platform}</span>
                <ArrowRight className="w-4 h-4 text-slate-400 ml-auto" />
              </button>
            ))}
          </div>
        </div>
      </Modal>

      {/* Find Lenders Modal */}
      <Modal isOpen={activeModal === 'lenders'} onClose={() => { setActiveModal(null); setAppliedLender(null); }} title="Available Lending Partners">
        <div className="space-y-5">
          {appliedLender ? (
            <div className="space-y-4">
              <div className="p-6 bg-emerald-50 rounded-2xl border border-emerald-100 text-center">
                <div className="w-16 h-16 bg-emerald-500 rounded-full flex items-center justify-center mx-auto mb-4">
                  <CheckCircle2 className="w-8 h-8 text-white" />
                </div>
                <p className="text-lg font-black text-emerald-700 mb-1">Application Submitted!</p>
                <p className="text-xs text-emerald-600 leading-relaxed">Your application to <span className="font-bold">{appliedLender.name}</span> for <span className="font-bold">{appliedLender.amount}</span> has been received.</p>
              </div>
              <div className="space-y-2">
                {[
                  { label: 'Application ID', value: appId, done: true },
                  { label: 'TrustScore Check', value: `${score}/100 — Qualified`, done: true },
                  { label: 'Lender Review', value: 'Processing...', done: false },
                  { label: 'Expected Response', value: 'Within 24 hours', done: false },
                ].map((step, i) => (
                  <div key={i} className="flex items-center justify-between p-3 bg-slate-50 rounded-xl">
                    <span className="text-xs font-medium text-slate-600">{step.label}</span>
                    <div className="flex items-center gap-2">
                      {step.done ? <CheckCircle2 className="w-4 h-4 text-emerald-500" /> : <Loader2 className="w-4 h-4 text-[#E8762E] animate-spin" />}
                      <span className="text-xs font-bold text-slate-900">{step.value}</span>
                    </div>
                  </div>
                ))}
              </div>
              <div className="p-4 bg-orange-50 rounded-2xl border border-orange-100">
                <p className="text-xs text-slate-600 leading-relaxed"><span className="font-bold text-[#E8762E]">What's next?</span> The lender will review your SquadMind TrustScore and transaction history.</p>
              </div>
              <button onClick={() => { setActiveModal(null); setAppliedLender(null); showSuccess(`Application to ${appliedLender.name} submitted!`); }}
                className="w-full bg-[#001f3f] text-white font-bold py-3 rounded-xl text-sm hover:bg-[#002b55] transition-colors cursor-pointer">Done</button>
            </div>
          ) : (
            <>
              <div className="p-4 bg-emerald-50 rounded-2xl border border-emerald-100 flex items-center gap-3">
                <ShieldCheck className="w-5 h-5 text-emerald-500 shrink-0" />
                <p className="text-xs text-emerald-700 font-bold">Your TrustScore of {score}/100 qualifies you for all offers below</p>
              </div>
              {lenders.map((lender, i) => (
                <div key={i} className="p-5 bg-slate-50 rounded-2xl border border-slate-100">
                  <div className="flex items-start justify-between mb-3">
                    <div><p className="text-sm font-black text-slate-900">{lender.name}</p><span className="text-[10px] font-bold text-slate-400">{lender.badge}</span></div>
                    <p className="text-xl font-black text-[#001f3f]">{lender.amount}</p>
                  </div>
                  <div className="grid grid-cols-3 gap-2 mb-4">
                    {[{ l: 'Rate', v: lender.rate }, { l: 'Duration', v: lender.duration }, { l: 'Type', v: lender.type }].map((item, j) => (
                      <div key={j} className="bg-white rounded-xl p-2 text-center">
                        <p className="text-[10px] text-slate-400 uppercase">{item.l}</p>
                        <p className="text-xs font-black text-slate-900">{item.v}</p>
                      </div>
                    ))}
                  </div>
                  <button onClick={() => handleApplyLender(lender)} disabled={!!applyingLender}
                    className="w-full bg-[#001f3f] text-white font-bold py-2.5 rounded-xl text-xs hover:bg-[#002b55] transition-colors cursor-pointer disabled:opacity-60 flex items-center justify-center gap-2">
                    {applyingLender === lender.name ? <><Loader2 className="w-3.5 h-3.5 animate-spin" /> Processing...</> : <><Zap className="w-3.5 h-3.5" /> Apply Now</>}
                  </button>
                </div>
              ))}
              <div className="p-4 bg-amber-50 rounded-2xl border border-amber-100">
                <p className="text-xs text-amber-700 leading-relaxed"><span className="font-bold">Note:</span> This is a demo feature.</p>
              </div>
            </>
          )}
        </div>
      </Modal>

      {/* History Modal */}
      <Modal isOpen={activeModal === 'history'} onClose={() => setActiveModal(null)} title="Historical TrustScore Data">
        <div className="space-y-5">
          <p className="text-xs text-slate-400">Your TrustScore trend over the last 6 months</p>
          <div className="relative h-32 flex items-end gap-2">
            {[{ month: 'Dec', score: 61 }, { month: 'Jan', score: 65 }, { month: 'Feb', score: 68 }, { month: 'Mar', score: 70 }, { month: 'Apr', score: 72 }, { month: 'May', score: score, current: true }].map((item, i) => (
              <div key={i} className="flex-1 flex flex-col items-center gap-1">
                <span className="text-[10px] font-black text-slate-900">{item.score}</span>
                <div className={`w-full rounded-t-lg ${item.current ? 'bg-[#E8762E]' : 'bg-slate-200'}`} style={{ height: `${(item.score / 100) * 100}%` }}></div>
                <span className={`text-[10px] font-bold ${item.current ? 'text-[#E8762E]' : 'text-slate-400'}`}>{item.month}</span>
              </div>
            ))}
          </div>
          <div className="space-y-3">
            <h4 className="text-sm font-bold text-slate-700">Score Changes</h4>
            {[
              { month: 'May 2026', change: '+2', reason: 'Improved fraud detection rate' },
              { month: 'Apr 2026', change: '+2', reason: 'Revenue consistency improved' },
              { month: 'Mar 2026', change: '+2', reason: 'New repeat customers added' },
              { month: 'Feb 2026', change: '+3', reason: 'Cash flow stabilized after Q1' },
              { month: 'Jan 2026', change: '+4', reason: 'First full month of Squad data' },
            ].map((item, i) => (
              <div key={i} className="flex items-center justify-between p-3 bg-slate-50 rounded-xl">
                <div><p className="text-xs font-bold text-slate-900">{item.month}</p><p className="text-[10px] text-slate-400">{item.reason}</p></div>
                <span className="text-sm font-black text-emerald-600">{item.change}</span>
              </div>
            ))}
          </div>
          <div className="p-4 bg-orange-50 rounded-2xl border border-orange-100">
            <p className="text-xs text-slate-600 leading-relaxed"><span className="font-bold text-[#E8762E]">Projection:</span> At your current growth rate, you could reach 80/100 by August 2026.</p>
          </div>
        </div>
      </Modal>

      {/* Component Detail Modal */}
      <Modal isOpen={activeModal === 'component'} onClose={() => setActiveModal(null)} title="Score Component Details">
        {selectedComponent && (
          <div className="space-y-5">
            <div className="p-5 bg-slate-50 rounded-2xl">
              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">{selectedComponent.label || selectedComponent.name}</p>
              <div className="flex items-baseline gap-2 mb-4">
                <span className="text-4xl font-black text-slate-900">{selectedComponent.score ?? selectedComponent.value ?? 0}</span>
                <span className="text-lg text-slate-400">/{selectedComponent.max ?? selectedComponent.max_score ?? 25}</span>
              </div>
              <div className="w-full h-3 bg-slate-200 rounded-full overflow-hidden">
                <div className={`h-full rounded-full ${(selectedComponent.color || getComponentColor(selectedComponent)) === 'red' ? 'bg-red-500' : (selectedComponent.color || getComponentColor(selectedComponent)) === 'emerald' ? 'bg-emerald-500' : 'bg-[#E8762E]'}`} style={{ width: getProgress(selectedComponent) }}></div>
              </div>
            </div>
            <div className="p-4 bg-orange-50 rounded-2xl border border-orange-100">
              <div className="flex items-start gap-3">
                <Info className="w-4 h-4 text-[#E8762E] mt-0.5 shrink-0" />
                <div>
                  <p className="text-[10px] font-bold text-[#E8762E] uppercase tracking-wider mb-2">What This Measures</p>
                  <p className="text-sm text-slate-600 leading-relaxed">{componentDetails[selectedComponent.label || selectedComponent.name]?.desc || 'This component measures a key financial health indicator.'}</p>
                </div>
              </div>
            </div>
            <div className="p-4 bg-[#001f3f] rounded-2xl text-white">
              <p className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-2">💡 How to Improve</p>
              <p className="text-sm text-slate-300 leading-relaxed">{componentDetails[selectedComponent.label || selectedComponent.name]?.tip || 'Focus on consistent transaction patterns.'}</p>
            </div>
            {(selectedComponent.score ?? 0) === 0 && (
              <div className="p-4 bg-red-50 rounded-2xl border border-red-100">
                <div className="flex items-start gap-3">
                  <TrendingDown className="w-4 h-4 text-red-500 mt-0.5 shrink-0" />
                  <p className="text-xs text-red-700 leading-relaxed"><span className="font-bold">Action Required:</span> This component is at 0. Improving it could add up to {selectedComponent.max ?? 15} points.</p>
                </div>
              </div>
            )}
          </div>
        )}
      </Modal>

      {/* ── SIDEBAR ── */}
      <aside className="w-[260px] bg-[#001f3f] flex flex-col justify-between shrink-0 h-full overflow-y-auto hidden md:flex">
        <div>
          <div className="p-8 pb-10">
            <h1 className="text-2xl font-bold tracking-tight text-white mb-0">SquadMind AI</h1>
            <p className="text-[10px] text-slate-400 mt-1 uppercase tracking-widest font-medium">POWERED BY SQUAD</p>
          </div>
          <nav className="px-4 space-y-1">
            {[
              { label: 'Dashboard', icon: <LayoutDashboard className="w-5 h-5" />, path: 'dashboard' },
              { label: 'Cash Flow', icon: <Banknote className="w-5 h-5" />, path: 'cashflow' },
              { label: 'Fraud Detection', icon: <ShieldAlert className="w-5 h-5" />, path: 'frauddetection' },
              { label: 'Alerts', icon: <Bell className="w-5 h-5" />, path: 'alerts' },
              { label: 'TrustScore', icon: <Award className="w-5 h-5" />, path: 'trustscore', active: true },
              { label: 'Settings', icon: <Settings className="w-5 h-5" />, path: 'settings' },
            ].map(item => (
              <button key={item.path} onClick={() => onNavigate(item.path)}
                className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors cursor-pointer ${item.active ? 'bg-[#E8762E] text-white' : 'text-slate-400 hover:text-white hover:bg-white/5'}`}>
                {item.icon}<span className="font-medium text-[15px]">{item.label}</span>
              </button>
            ))}
          </nav>
        </div>
        <div className="p-6 space-y-6">
          <div className="space-y-1">
            <button onClick={onLogout} className="w-full flex items-center gap-3 px-4 py-2 text-slate-400 hover:text-white transition-colors cursor-pointer">
              <LogOut className="w-4 h-4" /><span className="text-sm font-medium">Logout</span>
            </button>
          </div>
          <div className="pt-6 border-t border-white/5 flex items-center gap-3">
            <div className="w-10 h-10 rounded-lg bg-[#E8762E] flex items-center justify-center text-white font-bold">
              <User className="w-5 h-5" />
            </div>
            <div className="flex-1 min-w-0">
              <p className="text-sm font-bold text-white truncate">Lekan Adeyemi</p>
              <p className="text-[10px] text-slate-400 font-medium truncate">Merchant Admin</p>
            </div>
          </div>
        </div>
      </aside>

      {/* ── MAIN ── */}
      <main className="flex-1 flex flex-col h-full overflow-y-auto pb-20 md:pb-0">
        <header className="h-16 md:h-20 bg-white border-b border-slate-100 flex items-center justify-between px-4 md:px-8 shrink-0">
          <h2 className="text-xl md:text-2xl font-bold text-slate-900 leading-tight">TrustScore™</h2>
          <div className="flex items-center gap-2 md:gap-4">
            <button className="p-2 text-slate-400 hover:text-slate-600 transition-colors"><Mail className="w-5 h-5" /></button>
            <button className="p-2 text-slate-400 hover:text-slate-600 transition-colors relative">
              <Bell className="w-5 h-5" />
              <div className="absolute top-2 right-2 w-2 h-2 bg-red-500 rounded-full border-2 border-white"></div>
            </button>
            <div className="w-9 h-9 md:w-10 md:h-10 rounded-full bg-slate-100 flex items-center justify-center border border-slate-200">
              <User className="w-4 h-4 md:w-5 md:h-5 text-slate-400" />
            </div>
          </div>
        </header>

        <div className="p-4 md:p-8 max-w-[1400px] w-full mx-auto">
          {successMsg && (
            <div className="mb-6 p-4 bg-emerald-50 rounded-2xl border border-emerald-100 text-emerald-600 text-sm font-bold flex items-center gap-3">
              <CheckCircle2 className="w-5 h-5 shrink-0" />{successMsg}
            </div>
          )}
          {error && <div className="mb-6 p-4 bg-amber-50 rounded-2xl border border-amber-100 text-amber-600 text-sm font-medium">{error}</div>}

          <div className="grid grid-cols-1 lg:grid-cols-4 gap-8 mb-10">
            <div className="lg:col-span-3 bg-white rounded-2xl md:rounded-[40px] p-8 md:p-12 shadow-sm border border-slate-100 flex flex-col items-center justify-center relative overflow-hidden">
              <div className="relative w-full max-w-[340px] aspect-[2/1] mb-8">
                <svg className="w-full h-full" viewBox="0 0 100 50">
                  <path d="M5,50 A45,45 0 0,1 95,50" fill="none" stroke="#f1f5f9" strokeWidth="10" strokeLinecap="round" />
                  <path d={`M5,50 A45,45 0 0,1 ${endX},${endY}`} fill="none" stroke="#E8762E" strokeWidth="10" strokeLinecap="round" />
                </svg>
                <div className="absolute bottom-0 left-0 right-0 flex flex-col items-center">
                  <span className="text-4xl md:text-6xl font-bold text-slate-900">{score}<span className="text-xl md:text-2xl text-slate-300">/100</span></span>
                </div>
              </div>
              <div className="inline-flex items-center gap-2 px-4 py-1 bg-emerald-50 text-emerald-600 rounded-full text-[10px] font-bold tracking-wider mb-6 border border-emerald-100 uppercase">
                <ShieldCheck className="w-3.5 h-3.5" />{scoreLabel}
              </div>
              <h3 className="text-xl md:text-2xl font-bold text-slate-900 mb-2 text-center">Score is {score >= 70 ? 'Healthy' : score >= 50 ? 'Moderate' : 'Needs Improvement'}</h3>
              <p className="text-slate-500 text-sm font-medium mb-10 text-center">Based on last 90 days of Squad transactions</p>
              <div className="flex flex-col sm:flex-row gap-4 w-full sm:w-auto">
                <button onClick={downloadReport} className="flex items-center justify-center gap-2 bg-[#001f3f] text-white font-bold py-3.5 px-8 rounded-xl text-xs transition-all shadow-lg cursor-pointer hover:bg-[#002b55]">
                  <Download className="w-4 h-4" />Download Report
                </button>
                <button onClick={() => setActiveModal('share')} className="flex items-center justify-center gap-2 bg-white border border-slate-200 text-slate-600 font-bold py-3.5 px-8 rounded-xl text-xs transition-all cursor-pointer hover:bg-slate-50">
                  <Share2 className="w-4 h-4" />Share with Lender
                </button>
              </div>
            </div>

            <div className="bg-[#001f3f] rounded-2xl md:rounded-[40px] p-8 text-white relative overflow-hidden flex flex-col">
              <h4 className="text-lg font-bold mb-6">Instant Insights</h4>
              <div className="space-y-6 flex-1">
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center shrink-0">
                    <TrendingUp className="w-5 h-5 text-emerald-400" />
                  </div>
                  <div><p className="text-sm font-bold">Revenue Up {revenueChange}%</p><p className="text-[10px] text-slate-400">Month-over-month growth trend is positive.</p></div>
                </div>
                <div className="flex items-start gap-4">
                  <div className="w-10 h-10 rounded-xl bg-white/10 flex items-center justify-center shrink-0">
                    <ShieldAlert className="w-5 h-5 text-red-400" />
                  </div>
                  <div><p className="text-sm font-bold">Fraud Alerts</p><p className="text-[10px] text-slate-400">{fraudAlerts} flagged transactions requiring review.</p></div>
                </div>
                <button onClick={() => setActiveModal('history')}
                  className="w-full flex items-center justify-center gap-2 px-4 py-2.5 bg-white/10 hover:bg-white/20 text-white text-xs font-bold rounded-xl transition-colors cursor-pointer">
                  <History className="w-4 h-4" /> View Score History
                </button>
              </div>
              <div className="mt-8 pt-6 border-t border-white/5">
                <div className="h-12 flex items-end gap-1">
                  {[30, 45, 35, 55, 40, 65, 50, 75, 60, 85].map((h, i) => (
                    <div key={i} className="flex-1 bg-[#E8762E]/40 rounded-t-sm" style={{ height: `${h}%` }}></div>
                  ))}
                </div>
              </div>
            </div>
          </div>

          {/* Score Breakdown */}
          <div className="mb-12">
            <div className="flex justify-between items-end mb-6">
              <div>
                <h3 className="text-xl font-bold text-slate-900 mb-1">Score Breakdown</h3>
                <p className="text-sm text-slate-400 font-medium">Click any component to see details and improvement tips</p>
              </div>
              <button onClick={() => setActiveModal('history')} className="text-xs font-bold text-[#001f3f] hover:underline transition-all cursor-pointer">View Historical Data</button>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-5 gap-4">
              {scoreComponents.map((metric, i) => {
                const color = metric.color || getComponentColor(metric);
                const progress = metric.progress || getProgress(metric);
                const scoreVal = metric.score ?? metric.value ?? 0;
                const maxVal = metric.max ?? metric.max_score ?? 25;
                const subLabel = metric.sub || metric.status || '';
                return (
                  <div key={i} onClick={() => { setSelectedComponent(metric); setActiveModal('component'); }}
                    className={`bg-white rounded-2xl p-6 shadow-sm border border-slate-100 flex flex-col cursor-pointer hover:shadow-md hover:border-[#E8762E]/30 transition-all group ${color === 'red' ? 'border-l-4 border-l-red-500' : ''}`}>
                    <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest mb-4 leading-tight group-hover:text-[#E8762E] transition-colors">{metric.label || metric.name}</p>
                    <div className="flex items-baseline justify-between mb-4">
                      <span className="text-2xl font-bold text-slate-900">{scoreVal}<span className="text-sm text-slate-300">/{maxVal}</span></span>
                      <span className={`text-[9px] font-black tracking-tighter ${color === 'red' ? 'text-red-500' : color === 'emerald' ? 'text-emerald-500' : 'text-[#E8762E]'}`}>{subLabel}</span>
                    </div>
                    <div className="mt-auto h-1.5 bg-slate-50 rounded-full overflow-hidden">
                      <div className={`h-full ${color === 'red' ? 'bg-red-500' : color === 'emerald' ? 'bg-emerald-500' : 'bg-[#E8762E]'}`} style={{ width: progress }}></div>
                    </div>
                    <p className="text-[9px] text-[#E8762E] font-bold mt-3 opacity-0 group-hover:opacity-100 transition-opacity">Click for details →</p>
                  </div>
                );
              })}
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-12">
            <div className="bg-white rounded-[32px] p-8 md:p-10 shadow-sm border border-slate-100">
              <div className="flex items-center gap-3 mb-8">
                <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center">
                  <Info className="w-5 h-5 text-[#E8762E]" />
                </div>
                <h4 className="text-lg font-bold text-slate-900">What This Means</h4>
              </div>
              <p className="text-slate-500 text-sm md:text-base leading-relaxed mb-10 font-medium opacity-90">{explanation}</p>
              <div className="p-6 bg-[#f8fafc] rounded-2xl border-l-4 border-slate-900">
                <h5 className="text-sm font-bold text-slate-900 mb-2">Growth Opportunity</h5>
                <p className="text-xs text-slate-500 leading-relaxed font-medium">Your Growth Trend metric is currently low because of seasonal adjustments. Reaching a score of 80+ could unlock lower interest rates.</p>
              </div>
            </div>

            <div className="bg-white rounded-[32px] p-8 md:p-10 shadow-sm border border-slate-100 flex flex-col">
              <div className="flex items-center gap-3 mb-8">
                <div className="w-10 h-10 rounded-xl bg-orange-50 flex items-center justify-center">
                  <Landmark className="w-5 h-5 text-[#E8762E]" />
                </div>
                <h4 className="text-lg font-bold text-slate-900">Lender Ready</h4>
              </div>
              <div className="space-y-5 mb-10 flex-1">
                {["Identity Verified", "Squad Account Active (> 1yr)", "Transaction History Audited", "TrustScore Meeting Minimum Threshold"].map((step, i) => (
                  <div key={i} className="flex items-center gap-4">
                    <CheckCircle2 className="w-5 h-5 text-emerald-500" />
                    <span className="text-sm font-bold text-slate-700">{step}</span>
                  </div>
                ))}
              </div>
              <div className="p-8 bg-orange-50/30 rounded-3xl border border-orange-100/50">
                <p className="text-xs font-bold text-slate-500 mb-6 text-center">You are ready to apply for business credit</p>
                <button onClick={() => { setAppliedLender(null); setActiveModal('lenders'); }}
                  className="w-full bg-[#E8762E] hover:bg-[#E8762E]/90 text-white font-black py-4 rounded-xl flex items-center justify-center gap-3 transition-all shadow-lg shadow-[#E8762E]/20 cursor-pointer">
                  Find Lenders <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>

          <footer className="py-12 border-t border-slate-100 mt-12 text-center md:text-left flex flex-col md:flex-row justify-between items-center gap-6">
            <div className="flex items-center gap-8 text-[10px] font-bold text-slate-300 uppercase tracking-widest">
              <span className="text-slate-400">POWERED BY SQUAD</span>
              <a href="#" className="hover:text-[#E8762E] transition-colors">Privacy Policy</a>
              <a href="#" className="hover:text-[#E8762E] transition-colors">Terms of Service</a>
            </div>
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-widest">© 2026 SQUADMIND v2.4.1</p>
          </footer>
        </div>
      </main>

      <nav className="fixed bottom-0 left-0 w-full bg-white border-t border-slate-100 flex items-center justify-around py-3 md:hidden z-50">
        <button onClick={() => onNavigate('dashboard')} className="flex flex-col items-center gap-1 text-slate-400"><LayoutDashboard className="w-5 h-5" /><span className="text-[10px] font-bold">Home</span></button>
        <button onClick={() => onNavigate('cashflow')} className="flex flex-col items-center gap-1 text-slate-400"><Banknote className="w-5 h-5" /><span className="text-[10px] font-bold">Cash</span></button>
        <button onClick={() => onNavigate('frauddetection')} className="flex flex-col items-center gap-1 text-slate-400"><ShieldAlert className="w-5 h-5" /><span className="text-[10px] font-bold">Fraud</span></button>
        <button onClick={() => onNavigate('trustscore')} className="flex flex-col items-center gap-1 text-[#E8762E]"><Award className="w-5 h-5" /><span className="text-[10px] font-bold">Score</span></button>
        <button onClick={() => onNavigate('settings')} className="flex flex-col items-center gap-1 text-slate-400"><Settings className="w-5 h-5" /><span className="text-[10px] font-bold">More</span></button>
      </nav>
    </div>
  );
}

export default TrustScore;
